name: Build GUI binaries

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install pyinstaller
      - name: Build (one-folder using spec)
        run: |
          # Use the provided spec for reproducible builds
          pyinstaller --noconfirm scan_port_gui.spec
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: scan_port_gui-linux
          path: dist/scan_port_gui

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install pyinstaller
      - name: Build (one-folder using spec)
        run: |
          pyinstaller --noconfirm scan_port_gui.spec
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: scan_port_gui-windows
          path: dist/scan_port_gui
